// <auto-generated />
using System;
using IBM_WebApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IBM_WebApi.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20210712160731_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IBM_WebApi.Models.PCs", b =>
                {
                    b.Property<Guid>("ID_Pc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_Cpu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_Gpu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_Ram")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Pret")
                        .HasColumnType("int");

                    b.Property<bool?>("Sters")
                        .HasColumnType("bit");

                    b.HasKey("ID_Pc");

                    b.HasIndex("ID_Cpu");

                    b.HasIndex("ID_Gpu");

                    b.HasIndex("ID_Ram");

                    b.ToTable("Pcs");
                });

            modelBuilder.Entity("IBM_WebApi.Models.PlaciVideo", b =>
                {
                    b.Property<Guid>("ID_Gpu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pret")
                        .HasColumnType("int");

                    b.Property<string>("Producator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Sters")
                        .HasColumnType("bit");

                    b.Property<string>("Tip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Gpu");

                    b.ToTable("PlaciVideo");
                });

            modelBuilder.Entity("IBM_WebApi.Models.Procesoare", b =>
                {
                    b.Property<Guid>("ID_Cpu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Chipset")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pret")
                        .HasColumnType("int");

                    b.Property<string>("Producator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Sters")
                        .HasColumnType("bit");

                    b.HasKey("ID_Cpu");

                    b.ToTable("Procesoare");
                });

            modelBuilder.Entity("IBM_WebApi.Models.Ram", b =>
                {
                    b.Property<Guid>("ID_Ram")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Memorie")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pret")
                        .HasColumnType("int");

                    b.Property<string>("Producator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Sters")
                        .HasColumnType("bit");

                    b.HasKey("ID_Ram");

                    b.ToTable("Ram");
                });

            modelBuilder.Entity("IBM_WebApi.Models.User", b =>
                {
                    b.Property<Guid>("Id_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("Sters")
                        .HasColumnType("bit");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("bit");

                    b.HasKey("Id_User");

                    b.ToTable("User");
                });

            modelBuilder.Entity("IBM_WebApi.Models.PCs", b =>
                {
                    b.HasOne("IBM_WebApi.Models.Procesoare", "procesor")
                        .WithMany()
                        .HasForeignKey("ID_Cpu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IBM_WebApi.Models.PlaciVideo", "placaVideo")
                        .WithMany()
                        .HasForeignKey("ID_Gpu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IBM_WebApi.Models.Ram", "ram")
                        .WithMany()
                        .HasForeignKey("ID_Ram")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("placaVideo");

                    b.Navigation("procesor");

                    b.Navigation("ram");
                });
#pragma warning restore 612, 618
        }
    }
}
